/**
 * HML Template Generator for Antigravity
 *
 * This module generates the HWPML (HML) structure from scratch.
 * It defines custom styles, char shapes, and document settings that are unique to Antigravity,
 * ensuring no proprietary data from other services is copied.
 */

// Helper to generate a random ID to avoid collisions/tracking
const generateId = () => Math.floor(Math.random() * 2000000000);

export const getAntigravityHeader = (title: string = 'Antigravity Exam', mappingTableContent: string = ''): string => {
  if (!mappingTableContent) {
    // Minimal fallback if no mapping table (Should not happen in prod flow)
    mappingTableContent = `
      <BINDATALIST Count="0" />
      <FACENAMELIST Count="1"><FONT Id="0" Name="함초롬바탕" Type="ttf" /></FACENAMELIST>
      <BORDERFILLLIST Count="1">
        <BORDERFILL Id="1" ThreeD="false" Shadow="false"><LEFTBORDER Type="None" Width="0.1mm" /><RIGHTBORDER Type="None" Width="0.1mm" /><TOPBORDER Type="None" Width="0.1mm" /><BOTTOMBORDER Type="None" Width="0.1mm" /><DIAGONAL Type="None" Crooked="false" /></BORDERFILL>
      </BORDERFILLLIST>
      <CHARSHAPELIST Count="1">
        <CHARSHAPE Id="0" Height="1000" TextColor="0" ShadeColor="4294967295" UseFontSpace="false" UseKerning="false" Symbolic="false" BorderFillId="1" Hangul="0" Latin="0" Hanja="0" Japanese="0" Other="0" Symbol="0" User="0"><FONTID Hangul="0" Latin="0" Hanja="0" Japanese="0" Other="0" Symbol="0" User="0" /><RATIO Hangul="100" Latin="100" Hanja="100" Japanese="100" Other="100" Symbol="100" User="100" /><CHARSPACING Hangul="0" Latin="0" Hanja="0" Japanese="0" Other="0" Symbol="0" User="0" /><RELSIZE Hangul="100" Latin="100" Hanja="100" Japanese="100" Other="100" Symbol="100" User="100" /><CHAROFFSET Hangul="0" Latin="0" Hanja="0" Japanese="0" Other="0" Symbol="0" User="0" /></CHARSHAPE>
      </CHARSHAPELIST>
      <TABDEFLIST Count="1"><TABDEF Id="0" AutoTabLeft="false" AutoTabRight="false" /></TABDEFLIST>
      <NUMBERINGLIST Count="0" />
      <BULLETLIST Count="0" />
      <PARASHAPELIST Count="1">
        <PARASHAPE Id="0" Align="Justify" BreakLatinWord="Keep" BreakNonLatinWord="Break" Condense="0" FontLineHeight="false" HeadingType="None" KeepLines="false" KeepWithNext="false" LineWrap="Break" PageBreakBefore="false" SnapToGrid="true" TabDef="0" VerAlign="Baseline" WidowOrphan="false"><PARAMARGIN Indent="0" Left="0" LineSpacing="160" LineSpacingType="Percent" Prev="0" Next="0" Right="0" /></PARASHAPE>
      </PARASHAPELIST>
      <STYLELIST Count="1">
         <STYLE Id="0" Type="Para" Name="Normal" EngName="Normal" CharShape="0" ParaShape="0" NextStyle="0" />
      </STYLELIST>
    `;
  }

  return `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<HWPML Style="embed" SubVersion="8.0.0.0" Version="2.8">
  <HEAD SecCnt="1">
    <DOCSUMMARY>
      <TITLE>${title}</TITLE>
      <SUBJECT>Mathematics Exam</SUBJECT>
      <AUTHOR>Antigravity AI</AUTHOR>
      <DATE>${new Date().toISOString().split('T')[0]}</DATE>
      <KEYWORDS>Antigravity, Math, Exam</KEYWORDS>
      <COMMENTS>Generated by Antigravity AI Engine</COMMENTS>
    </DOCSUMMARY>
    <DOCSETTING>
      <BEGINNUMBER Endnote="1" Equation="1" Footnote="1" Page="1" Picture="1" Table="1" />
      <CARETPOS List="0" Para="0" Pos="0" />
    </DOCSETTING>
    <MAPPINGTABLE>
      ${mappingTableContent}
    </MAPPINGTABLE>
    <COMPATIBLEDOCUMENT TargetProgram="HancomOffice">
      <LAYOUTCOMPATIBILITY />
    </COMPATIBLEDOCUMENT>
  </HEAD>
  <BODY>
    <SECTION Id="0">
      <SECDEF CharGrid="0" FirstBorder="false" FirstFill="false" LineGrid="0" SpaceWidth="0" TextDirection="0" VerticalPageAlign="0">
        <STARTNUMBER Equation="0" Page="0" Picture="0" Table="0" />
        <HIDE Border="false" Fill="false" Footer="false" Header="false" MasterPage="false" PageNum="false" />
        <PAGEDEF GutterType="Left" Height="297mm" Landscape="0" Width="210mm">
          <PAGEMARGIN Bottom="15mm" Footer="0mm" Gutter="0mm" Header="0mm" Left="20mm" Right="20mm" Top="20mm" />
        </PAGEDEF>
        <COLDEF Count="1" Layout="Left" SameGap="0" SameSize="true" Type="Newspaper">
          <COLORG Gap="0" Width="48189" />
        </COLDEF>
      </SECDEF>`;
};

export const getAntigravityTail = (tailContent: string = ''): string => {
  return `
    </SECTION>
  </BODY>
  <TAIL>
    ${tailContent}
  </TAIL>
</HWPML>`;
};
