import type {Metadata} from 'next';
import Link from 'next/link';
import Header from '@/components/Header';
import AccessPolicy from '@/components/AccessPolicy';
export const metadata:Metadata={title:'수학 시험지 만들기 사용법·무료 범위·파일 형식 | 수학ETF',description:'기출 5문항 체험부터 범위 선택, 문항 편집, HML 저장과 다운로드까지. 학생의 오답 연습과 교사의 수업용 출제를 안내합니다.',alternates:{canonical:'/guide'}};
export default function GuidePage(){return <><Header/><main className="guide-page"><p className="eyebrow mb-4">GETTING STARTED</p><h1>고르는 순간부터,<br/>시험지를 받는 순간까지.</h1><p className="guide-lead">먼저 문항을 살펴보고, 필요한 문제만 담아보세요.<br/>기출 5문항이 담긴 편집 화면에서 바로 시작할 수 있습니다.</p><div className="flex flex-wrap gap-3 mt-7"><Link className="product-button primary" href="/question-bank?demo=1&origin=guide">기출 5문항으로 시작 →</Link><Link className="product-button secondary" href="/schools">우리 학교 기출 찾기</Link></div>
 <section aria-label="시험지 만드는 순서" className="guide-steps"><article className="guide-step"><span>01 / FIND</span><h2>배운 범위를 고르세요.</h2><p>학교와 시험 회차, 과목과 단원을 선택하세요. 자동 출제도 선택한 자료 안에서 문항을 찾습니다. 원래 시험의 과목과 현재 문항 분류는 다를 수 있으니 단원을 함께 확인하세요.</p><Link href="/schools">학교 이름으로 찾아보기 ↗</Link></article><article className="guide-step"><span>02 / EDIT</span><h2>필요한 문제만 담으세요.</h2><p>문항 카드를 누르면 선택됩니다. 상세보기에서 수식과 그림을, 해설보기에서 풀이를 확인하세요. 담은 문항은 순서를 바꾸거나 빼면서 시험지를 다듬을 수 있습니다.</p><Link href="/question-bank?demo=1&origin=guide">편집 화면 직접 살펴보기 ↗</Link></article><article className="guide-step"><span>03 / EXPORT</span><h2>나만의 시험지로 받으세요.</h2><p>로그인 후 제목과 열당 문제 수를 정하고 저장하세요. 완료 화면에서 HML 파일을 받으면 됩니다. 한글에서 편집·인쇄할 수 있고, PDF로도 저장할 수 있습니다.</p><Link href="#format">파일 형식 알아보기 ↓</Link></article></section>
 <section className="guide-roles"><article id="student"><p className="eyebrow">FOR STUDENTS</p><h2>틀린 문제, 한 번 더.</h2><p>최근 시험지에서 ‘불러와 수정’을 누르세요. 맞힌 문제를 빼고, 다시 풀 문제만 남겨 새 시험지로 저장할 수 있습니다. 원래 시험지는 그대로 보관됩니다.</p><Link className="product-button secondary" href="/question-bank?demo=1&origin=student-guide">내 연습지 만들기 →</Link></article><article id="teacher"><p className="eyebrow">FOR TEACHERS</p><h2>같은 범위, 새로운 구성.</h2><p>‘같은 범위로 재출제’는 이전 문항을 제외하고 같은 자료에서 다시 고릅니다. 단원·난이도를 조절한 뒤 새 문항을 확인하세요. 특정 문항과 닮은 문제는 편집 화면의 ‘유사’로 찾을 수 있습니다.</p><Link className="product-button secondary" href="/question-bank?demo=1&origin=teacher-guide">수업용 시험지 만들기 →</Link></article></section>
 <section id="access"><AccessPolicy/></section><section className="guide-faq"><h2>궁금한 점을 먼저 정리했어요.</h2><details id="format"><summary>시험지는 어떤 파일로 받나요?</summary><p>직접 만든 시험지는 한글에서 편집할 수 있는 HML 파일입니다. 완성된 PDF를 바로 내려받는 기능과는 다릅니다. PDF가 필요하면 한글에서 HML을 연 뒤 ‘PDF로 저장’을 이용하세요.</p></details><details><summary>요청한 문항 수보다 적게 만들어졌어요.</summary><p>선택한 자료·단원·난이도와 중복 제외 조건을 모두 만족하는 문항이 부족한 경우입니다. 범위를 임의로 넓히지 않습니다. 안내된 문항을 먼저 확인하고 조건을 조정하거나 다른 자료를 선택하세요.</p></details><details><summary>같은 범위로 재출제하면 어떤 점이 달라지나요?</summary><p>이전 시험지에 사용한 문항을 제외합니다. 같은 유형의 유사문항을 보장하는 기능은 아니며, 선택 자료의 단원·난이도 조건에 맞춰 새로 구성합니다. 설정 도중 취소하면 현재 작업은 유지됩니다.</p></details><details><summary>로그인하거나 새로고침하면 담은 문제가 없어지나요?</summary><p>같은 브라우저에서는 최근 7일 이내의 초안을 이어서 만들 수 있습니다. 저장 전 초안은 다른 기기로 옮겨지지 않으므로, 완성한 시험지는 로그인 후 보관함에 저장해주세요.</p></details><details><summary>무료 자료와 유료 자료는 어떻게 구분하나요?</summary><p>출제용 자료의 무료 이용 기간과 무료 문제 PDF의 일일 한도는 위 이용 안내에 표시됩니다. 완성된 해설 PDF·HWP의 구매는 별도입니다. 자료별 제공 형식과 가격을 확인하세요.</p></details></section></main></>}
