import os
import sys
import json
import traceback

# Add current dir to path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from gemini_client import GeminiMathParser
from latex_hwp_compiler import compile_latex_to_hwp

class MockGeminiParser(GeminiMathParser):
    def __init__(self):
        pass

def test_pipeline(raw_json_string):
    parser = MockGeminiParser()
    # 1. Sanitize the raw text (as generated by AI)
    sanitized_text = parser._sanitize_json(raw_json_string)
    
    # 2. JSON Parser Extracts the Equation
    try:
        import json_repair
        parsed_json = json_repair.loads(sanitized_text)
        eq_text = parsed_json.get("eq", "")
    except Exception as e:
        return f"[JSON PARSE ERROR] {e}"
        
    # 3. AST Compiler translates to HWP
    try:
        hwp_output = compile_latex_to_hwp(eq_text)
        return hwp_output
    except Exception as e:
        return f"[COMPILER ERROR] {e}"

# ----------------- TEST CASES -----------------

test_cases = [
    # --- Category A: Hall of Fame (Past Crashing Bugs) ---
    {
        "name": "3 TIMES 4a (Missing space caused fusion)",
        "input": r'{"eq": "3 \\times 4a"}',
        "assert_not_in": ["3TIMES4a"] # HWP must separate 3 TIMES 4a to avoid parsing failure
    },
    {
        "name": "Cases row break missing (Line flattened)",
        "input": r'{"eq": "\\begin{cases} x & (x < 0) \\\\ y & (x \\ge 0) \\end{cases}"}',
        "assert_in": ["#"] # MUST contain row break separator
    },
    {
        "name": "\\text variable stringification",
        "input": r'{"eq": "\\overline{\\text{AB}} = 3"}',
        "assert_not_in": ["text", "mathrm"] # MUST NOT emit 'text' literal into HWP
    },
    {
        "name": "Small parenthesis scaling for Fractions",
        "input": r'{"eq": "\\left( \\frac{a}{b} \\right)"}',
        "assert_in": ["LEFT (", "RIGHT )"]
    },
    
    # --- Category B: High School Math Stress Test ---
    {
        "name": "Complex N-th root mapping",
        "input": r'{"eq": "\\sqrt[n]{x^2 + 1}"}',
        "assert_in": ["root", "of"]
    },
    {
        "name": "Sigma Limits (Math I/II)",
        "input": r'{"eq": "\\sum_{k=1}^{n} \\frac{1}{k}"}',
        "assert_in": ["sum _", "^"]
    },
    {
        "name": "Integral with Limits (Calculus)",
        "input": r'{"eq": "\\int_{a}^{b} f(x) dx"}',
        "assert_in": ["int _", "^"]
    },
    {
        "name": "Conjugate Complex Numbers (Math Upper)",
        "input": r'{"eq": "\\overline{a+bi} + \\overline{c+di}"}',
        "assert_in": ["overline {"]
    },
    {
        "name": "Vectors and Sets (Geometry/Set Theory)",
        "input": r'{"eq": "A \\subset B \\cup C \\cap D"}',
        "assert_in": ["subset", "cup", "cap"]
    },
    {
        "name": "3x3 Pmatrix",
        "input": r'{"eq": "\\begin{pmatrix} 1 & 2 & 3 \\\\ 4 & 5 & 6 \\\\ 7 & 8 & 9 \\end{pmatrix}"}',
        "assert_in": ["pmatrix", "#", "&"]
    },

    # --- Category C: AI Hallucination & Dirty JSON Simulation ---
    {
        "name": "Dirty: No spaces anywhere",
        "input": r'{"eq": "\\sum_{i=1}^n\\frac{1}{n}=10"}',
        "assert_not_in": ["\\frac", "\\sum"] # Command must be converted beautifully
    },
    {
        "name": "Dirty: Single unescaped backslashes by AI (JSON failure simulation)",
        "input": r'{"eq": "\frac{A}{B} \begin{cases} x \ y \end{cases}"}',
        "assert_in": ["over", "cases", "#"] # Sanitize JSON must rescue this
    },
    {
        "name": "Dirty: Newlines inside string (Gemini 3 Pro quirk)",
        "input": '{"eq": "\\begin{cases}\nx\n\\\\\ny\n\\end{cases}"}',
        "assert_in": ["cases", "#"]
    },
    {
        "name": "Dirty: Literal \\text with spaces inside",
        "input": r'{"eq": "\\text{최 소 값} + \\mathrm{A B}"}',
        "assert_not_in": ["text", "mathrm"] # Must strip or convert safely without breaking HWP
    }
]

failed_cases = []

print("========================================")
print("🚀 HWP AST COMPILER HEADLESS TEST SUITE")
print("========================================\n")

for i, tc in enumerate(test_cases):
    name = tc["name"]
    raw_json = tc["input"]
    
    print(f"[{i+1}/{len(test_cases)}] {name}")
    print(f"  Input JSON: {raw_json}")
    
    # Run
    output = test_pipeline(raw_json)
    print(f"  Output HWP: {output}")
    
    status = "PASS"
    fail_reason = ""
    
    # Assertions
    if "[JSON PARSE ERROR]" in output or "[COMPILER ERROR]" in output:
        status = "FAIL"
        fail_reason = output
    else:
        if "assert_in" in tc:
            for req in tc["assert_in"]:
                if req not in output:
                    status = "FAIL"
                    fail_reason = f"Missing required token: '{req}'"
                    break
        
        if "assert_not_in" in tc:
            for req in tc["assert_not_in"]:
                if req in output:
                    status = "FAIL"
                    fail_reason = f"Disallowed token found: '{req}'"
                    break
                    
    if status == "FAIL":
        print(f"  ❌ {status}: {fail_reason}")
        failed_cases.append({"name": name, "reason": fail_reason, "output": output})
    else:
        print(f"  ✅ {status}")
    print("-" * 40)

print("\n========================================")
print(f"🏁 TEST SUMMARY: {len(test_cases) - len(failed_cases)} / {len(test_cases)} PASSED")
print("========================================")

if failed_cases:
    print("🚨 THE FOLLOWING TESTS FAILED AND MUST BE FIXED BEFORE RELEASE:")
    for fc in failed_cases:
        print(f" - {fc['name']}: {fc['reason']}")
    sys.exit(1)
else:
    print("✨ ALL TESTS PASSED. The pipeline is mathematically stable and Hallucination-proof.")
    sys.exit(0)
