-- Migration: Create Questions Table
-- Date: 2026-01-12
-- Description: Creates the 'questions' table if it doesn't exist, with all necessary columns.

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Core Content
  source_db_id text,          -- e.g., "School_2025_1st_Math"
  question_number integer,    -- e.g., 1, 2, 3
  content_xml text,           -- The HML/XML content
  plain_text text,            -- Extracted text for search
  
  -- Metadata for Filtering
  subject text,               -- e.g., "Math1"
  unit text,                  -- e.g., "Polynomials"
  difficulty text,            -- e.g., "High", "Medium"
  
  -- Detailed Metadata (New)
  region text,                -- e.g., "Seoul"
  district text,              -- e.g., "Gangnam"
  school text,                -- e.g., "Kyunggi High"
  grade text,                 -- e.g., "High1"
  year text,                  -- e.g., "2025"
  semester text               -- e.g., "1st Semester"
);

-- Enable RLS (Row Level Security) - Optional but recommended
alter table public.questions enable row level security;

-- Create policy to allow all actions for now (since this is internal/admin tool usage)
-- Or just allow public read/write if easy development is preferred
create policy "Enable all access for all users" on public.questions
for all using (true) with check (true);

-- Create Filter Index
create index if not exists idx_questions_meta 
on public.questions (region, district, school, grade, subject);
